#!/usr/bin/env python3
"""Re-chrome the Brasil 2C water-security map for Ponte em Cena.

    python3 tools/make-water-map.py      # -> mapa-agua/index.html

Source: ~/Claude/dutch-flow-tech-brazil/agrotechdaholanda/mapa-do-clima.html,
itself generated by that project's tools/brasil2c/mapa.py. We transform its
OUTPUT rather than editing its generator, so the DFT site keeps its own chrome
and neither copy drifts into the other.

What carries over untouched: the inline SVG of all 5,570 municipalities, the
data array, and the interaction (search, indicator tabs, detail panel, zoom,
popover). Those are the expensive, correct parts.

What changes: fonts to Space Grotesk and Gelasio, the CSS custom properties to
the Ponte palette, the branding, and the choropleth ramp.

The ramp change is deliberate, not cosmetic. The source runs blue to orange;
ours runs green to gold to orange, which is the brand gradient's own journey
and reads as less-to-more of one thing rather than two opposed camps. It is
solved for monotonic lightness so it still works in greyscale and for red-green
colour blindness — see the RAMPA constants for why the obvious version fails.

Attribution is a CONDITION OF USE, not a courtesy: the Lobelia source line with
its access date, the link to portal.brasil2c.com, and the screening-level
caveat all travel with the map. So does the note that the composite index is
our calculation and not Lobelia's.
"""

from pathlib import Path
import re

SRC = Path.home() / "Claude/dutch-flow-tech-brazil/agrotechdaholanda/mapa-do-clima.html"
ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "mapa-agua" / "index.html"

# Ponte palette, mapped onto the source's variable roles.
TOKENS = {
    "--orange:#FF914D": "--orange:#E85D04",
    "--blue:#38B6FF": "--blue:#007F33",      # the cool role becomes BR-green
    "--navy:#14263C": "--navy:#1A1A1A",
    "--paper:#FBFAF7": "--paper:#FAF7F2",
    "--soft:#55677D": "--soft:#3D3D3D",
    "--line:#E8E4DB": "--line:#E4DFD6",
    "--panel:#14263C": "--panel:#1A1A1A",
}

# Green → gold → orange, the brand gradient's own journey (BR · encontro · NL).
#
# Solved, not eyeballed. A choropleth has to survive greyscale and red-green
# colour blindness, which means LIGHTNESS must fall monotonically across the
# ramp — hue alone is not a channel everyone has. The obvious version fails
# that test: Ponte gold #E0A500 (relative luminance 0.428) is LIGHTER than
# mid-green #4FA873 (0.309), so a naive green→gold→orange ramp gets brighter at
# step 4 and steps 3 and 5 become indistinguishable in greyscale.
#
# These six were solved by walking hue 148° → 20° at brand-like saturation
# while fitting each step to a falling luminance target. Result: strictly
# monotonic, smallest step 0.091, and every stop sits near a real brand colour
# (green tint, green mid, gold, orange, orange dark).
RAMP_OLD = "const RAMPA = ['#E9EEF3', '#BFE3F8', '#79C9F2', '#FFC98F', '#FF914D', '#D4541E'];"
RAMP_NEW = "const RAMPA = ['#C8F0DB', '#94E1B7', '#62CD62', '#C5940C', '#DB5909', '#B0420B'];"

FONTS = """  @font-face { font-family:'Space Grotesk'; font-weight:300 700; font-display:optional;
    src:url('../fonts/spacegrotesk-var.woff2') format('woff2'); }
  @font-face { font-family:'Gelasio'; font-weight:400 700; font-display:optional;
    src:url('../fonts/gelasio-var.woff2') format('woff2'); }"""


def die(msg):
    raise SystemExit(f"make-water-map: {msg}")


def main():
    if not SRC.exists():
        die(f"source not found: {SRC}")
    s = SRC.read_text(encoding="utf-8")

    style = re.search(r"<style>(.*?)</style>", s, re.S)
    script = re.search(r"<script>(.*?)</script>", s, re.S)
    if not (style and script):
        die("could not locate the style or script block")

    css = style.group(1)
    js = script.group(1)

    # the map section is the first <section>; the rest is DFT editorial
    sec_start = s.index("<section>")
    sec_end = s.index("<section>", sec_start + 1)
    section = s[sec_start:sec_end]

    # ── fonts ───────────────────────────────────────────────────────────
    css = re.sub(r"\s*@font-face \{ font-family:'Poppins'.*?\}\n", "\n", css, flags=re.S)
    css = FONTS + "\n" + css
    css = css.replace("font-family:'Poppins',-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif",
                      "font-family:'Gelasio',Georgia,serif")
    css = css.replace("'Poppins'", "'Space Grotesk'")

    # ── palette ─────────────────────────────────────────────────────────
    missed = [k for k in TOKENS if k not in css]
    if missed:
        die(f"token(s) not found, source may have changed: {missed}")
    for old, new in TOKENS.items():
        css = css.replace(old, new)

    # headings should be the wordmark face, as everywhere else on the site
    css += ("\n  h1,h2,h3,.aba,.rot,.assinatura,button{font-family:'Space Grotesk',sans-serif;}"
            "\n  body{background:var(--paper);}")

    # ── colour ramp ─────────────────────────────────────────────────────
    if RAMP_OLD not in js:
        die("colour ramp not found, source may have changed")
    js = js.replace(RAMP_OLD, RAMP_NEW)

    # ── drop the commercial composite ───────────────────────────────────
    # The fifth tab, "Relevância Agrotech", is our own index built to answer
    # "where should we sell". It is the commercial layer of the DFT work and it
    # does not belong on a cultural-programme site, whatever it is renamed to.
    # The four remaining tabs are Lobelia's measurements, which is what an
    # oficina actually needs. Removing the tab is cleaner than relabelling a
    # sales instrument.
    before = js
    js = re.sub(r',\s*\{"id":\s*"agro".*?\}\s*(?=\])', "", js, count=1, flags=re.S)
    if js == before:
        die("could not remove the 'agro' composite tab; source may have changed")

    # the detail panel carried a score row for that same composite; leaving it
    # would show a number with nothing on the page explaining it
    before = section
    section = re.sub(r'<div class="posicao">\s*<span class="rot">Relev[^<]*Agrotech</span>.*?</div>',
                     "", section, count=1, flags=re.S)
    if section == before:
        die("could not remove the composite row from the detail panel")
    js = re.sub(r'/\* -+ relev[^*]*Agrotech.*?-+ \*/', "", js, count=1, flags=re.S)
    # ...and the line that WRITES to the element we just deleted. Leaving it in
    # made getElementById('prank') return null, so `null.textContent = ...`
    # threw a TypeError partway through the selection handler: the panel filled
    # (those lines run first) but the map highlight and the popover never did,
    # because the throw aborted the rest of the function.
    before_prank = js
    js = re.sub(r"\n\s*document\.getElementById\('prank'\)\.textContent[^;]*;", "", js, count=1)
    if js == before_prank:
        die("the #prank writer was not found; removing the element would break selection")



    # ── drag to pan ─────────────────────────────────────────────────────
    # The source has zoom buttons but no panning at all: once zoomed you could
    # only re-centre by selecting another município. Dragging is the obvious
    # gesture and it does not touch the wheel, so the source's reasoning for
    # avoiding wheel-zoom (it swallows page scroll and traps the reader) still
    # holds.
    #
    # Two details that matter. A click must still select, so a drag only counts
    # after 4px of movement and a real drag swallows the click that follows it.
    # And touch-action is set per zoom level: at full extent there is nothing to
    # pan, so the page must scroll normally over the map; once zoomed in,
    # panning wins. That keeps the no-trapping promise the source made.
    anchor = "document.getElementById('zmais').addEventListener('click'"
    if anchor not in js:
        die("zoom button handler not found; cannot attach panning")
    js = js.replace(anchor, """/* ---------- arrastar para mover ---------- */
(function () {
  var arrastando = false, moveu = false, x0 = 0, y0 = 0, vx0 = 0, vy0 = 0;
  function escala() { var r = svg.getBoundingClientRect();
    return r.width ? vb.w / r.width : 1; }
  palco.style.cursor = 'grab';
  palco.addEventListener('pointerdown', function (e) {
    if (e.button !== 0 && e.pointerType === 'mouse') return;
    arrastando = true; moveu = false;
    x0 = e.clientX; y0 = e.clientY; vx0 = vb.x; vy0 = vb.y;
    /* NO setPointerCapture here. Capturing on pointerdown retargets the click
       that follows to the capturing element, so it never reaches the <path>
       and selecting a município silently stops working. Capture is taken below,
       only once the movement threshold proves this is a drag and not a click. */
  });
  palco.addEventListener('pointermove', function (e) {
    if (!arrastando) return;
    var dx = e.clientX - x0, dy = e.clientY - y0;
    if (!moveu && Math.abs(dx) + Math.abs(dy) < 4) return;  /* still a click */
    if (!moveu) {
      moveu = true;
      palco.style.cursor = 'grabbing';
      try { palco.setPointerCapture(e.pointerId); } catch (err) {}
    }
    var k = escala();
    vb.x = vx0 - dx * k; vb.y = vy0 - dy * k;
    limitar(); aplicar();
  });
  function soltar(e) {
    if (!arrastando) return;
    arrastando = false;
    palco.style.cursor = 'grab';
    try { palco.releasePointerCapture(e.pointerId); } catch (err) {}
  }
  palco.addEventListener('pointerup', soltar);
  palco.addEventListener('pointercancel', soltar);
  /* a drag that ends over a município must not also select it */
  palco.addEventListener('click', function (e) {
    if (moveu) { e.stopPropagation(); e.preventDefault(); moveu = false; }
  }, true);
})();
""" + anchor, 1)

    # let the page scroll over the map until there is something to pan
    js = js.replace("""  document.getElementById('zmenos').disabled = f <= 1.01;""",
                    """  document.getElementById('zmenos').disabled = f <= 1.01;
  palco.style.touchAction = f > 1.01 ? 'none' : 'pan-y';""")

    # ── make the four KPI cards self-explanatory ────────────────────────
    # As inherited, the panel shows "56 → 138" with nothing saying what the two
    # numbers are, "-15 mm/déc" with nothing saying a minus means the rain is
    # going away, and a bare "20" for soil deficit with NO UNIT — the source
    # writes k3 without one. Each card gets a one-line explanation underneath,
    # and the missing unit is restored.
    for old, new in [
        ("""<div class="kpi quente"><div class="rot">Dias acima de 35 °C</div>
              <div class="val" id="k1"></div></div>""",
         """<div class="kpi quente"><div class="rot">Dias acima de 35 °C</div>
              <div class="val" id="k1"></div>
              <div class="exp">hoje &rarr; num mundo 2 °C mais quente</div></div>"""),
        ("""<div class="kpi agua"><div class="rot">Tendência da chuva</div>
              <div class="val" id="k2"></div></div>""",
         """<div class="kpi agua"><div class="rot">Tendência da chuva</div>
              <div class="val" id="k2"></div>
              <div class="exp" id="e2"></div></div>"""),
        ("""<div class="kpi agua"><div class="rot">Déficit de umidade no solo</div>
              <div class="val" id="k3"></div></div>""",
         """<div class="kpi agua"><div class="rot">Déficit de umidade no solo</div>
              <div class="val" id="k3"></div>
              <div class="exp">meses acumulados na série histórica</div></div>"""),
        ("""<div class="kpi"><div class="rot">Radiação solar</div>
              <div class="val" id="k4"></div></div>""",
         """<div class="kpi"><div class="rot">Radiação solar</div>
              <div class="val" id="k4"></div>
              <div class="exp">média anual</div></div>"""),
    ]:
        if old not in section:
            die("KPI card markup not found; source may have changed")
        section = section.replace(old, new)

    # the missing unit, and a plain-language reading of the rainfall sign
    js = js.replace("getElementById('k3').innerHTML = nb(g('solo'), 0);",
                    "getElementById('k3').innerHTML = `${nb(g('solo'), 0)} <small>meses</small>`;")
    before_js = js
    js = js.replace("document.getElementById('k4').innerHTML =",
                    """(function(){ var c = g('chuva'), e = document.getElementById('e2');
      if (e) e.textContent = (c === null || c === undefined) ? 'sem dado'
        : c < 0 ? 'a chuva vem caindo, medido entre 1980 e 2015'
        : c > 0 ? 'a chuva vem subindo, medido entre 1980 e 2015'
        : 'sem tendência clara, medido entre 1980 e 2015'; })();
    document.getElementById('k4').innerHTML =""")
    if js == before_js:
        die("k4 assignment not found; the rainfall explainer was not inserted")

    css += ("\n  .kpi .exp{font-family:'Gelasio',Georgia,serif;font-size:0.74rem;line-height:1.35;"
            "color:var(--soft);margin-top:6px;}"
            # The source coloured the water KPIs with its neutral blue. Ponte has
            # no blue, so mapping --blue onto BR-green turned "-15 mm/déc" green
            # — reading as good news on a card whose whole point is that the rain
            # is going away. These values go neutral; the heat card keeps its
            # orange, which is the one number that should alarm.
            "\n  .kpi.agua .val{color:var(--navy);}")

    # ── branding out of the map section ─────────────────────────────────
    section = re.sub(r'<svg class="hero-mark".*?</svg>', "", section, flags=re.S)
    section = section.replace("Agrotech da Holanda", "Ponte em Cena")

    page = f"""<!DOCTYPE html>
<!--
  GENERATED by tools/make-water-map.py from the Brasil 2C map in the
  dutch-flow-tech-brazil project. Do not hand-edit: re-run the script.

  Data: Lobelia Earth, "Brasil in a +2ºC World" (Lobelia + Instituto Itaúsa),
  accessed 07/08/2026. Attribution and the screening-level caveat are a
  condition of use and must stay on the page.
-->
<html lang="pt-BR">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'self'; form-action 'none'">
<title>Segurança hídrica no Brasil — mapa por município | Ponte em Cena</title>
<meta name="description" content="Mapa interativo dos 5.570 municípios brasileiros: tendência de chuva, dias acima de 35 °C, déficit de umidade do solo e radiação solar. Material de apoio das oficinas do Ponte em Cena.">
<link rel="canonical" href="https://ponte-em-cena.com.br/mapa-agua/">
<link rel="icon" type="image/svg+xml" href="../assets/favicon.svg">
<style>{css}</style>
</head>
<body>
<!-- <main> rather than the source's bare <section>: this page is served at its
     own URL as well as inside an iframe, and standalone it needs a main
     landmark. Without it axe reports landmark-one-main and the page loses a11y
     points for a reason that has nothing to do with the map. -->
<main>
{section}
</main>
<footer>
  <div class="wrap">
    <p><strong>Fonte dos dados:</strong> Lobelia Earth, <em>Brasil in a +2ºC World</em>,
    uma iniciativa da Lobelia e do Instituto Itaúsa, acessada em 07/08/2026 —
    <a href="https://portal.brasil2c.com/" target="_blank" rel="noopener noreferrer">portal.brasil2c.com</a>.</p>
    <p>Os dados são de <strong>nível de triagem</strong> e não substituem avaliação técnica
    em campo, estudo de impacto ambiental ou parecer jurídico. A tendência de chuva é
    medição observada entre 1980 e 2015, não projeção. O cenário de +2 °C não tem data
    de calendário.</p>
    <p>As quatro abas mostram medições da fonte. O índice composto que existe na
    versão original deste mapa foi <strong>retirado aqui</strong>: era cálculo
    nosso, feito para outra finalidade, e não pertence a este contexto.</p>
    <p class="assinatura">Ponte em Cena · material de apoio da oficina
    <a href="../oficinas/diagnosticar/">Diagnosticar</a>. Análise reaproveitada do
    trabalho do Regen Studio com a Dutch Flow Technology.</p>
  </div>
</footer>
<script>{js}</script>
</body>
</html>
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(page, encoding="utf-8")
    kb = OUT.stat().st_size / 1024
    print(f"  wrote mapa-agua/index.html ({kb:,.0f} KB)")
    print(f"  municipalities: {page.count('<path id=\"m')}")


if __name__ == "__main__":
    main()
